{
 "title": "FastAPI Observability Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(http_requests_total)" }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m]))"
    }
   ]
  },
  {
   "title": "Concurrent Requests",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "concurrent_requests" }
   ]
  },
  {
   "title": "Requests Per Second by Endpoint",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Error Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "DB-like p95 Latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{endpoint=\"db_like\"}[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Average Latency by Endpoint",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) by (endpoint) / sum(rate(http_request_duration_seconds_count[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Cache Hits vs Misses",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 20, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(db_cache_operations_total[1m])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "CPU-heavy Requests In Progress",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 20, "w": 12, "h": 8 },
   "targets": [
    { "expr": "cpu_heavy_requests_in_progress", "legendFormat": "cpu" }
   ]
  }
 ]
}